build: add ConfigMap build sources
RFE/bug 1540978

diff --git a/test/extended/testdata/builds/build-secrets/s2i-binary-dir/.s2i/bin/assemble b/test/extended/testdata/builds/build-secrets/s2i-binary-dir/.s2i/bin/assemble
--- a/test/extended/testdata/builds/build-secrets/s2i-binary-dir/.s2i/bin/assemble
+++ b/test/extended/testdata/builds/build-secrets/s2i-binary-dir/.s2i/bin/assemble
@@ -19,3 +19,21 @@ else
     echo "Unable to locate testsecret2 fixture files"
     exit 2
 fi 
+
+mkdir -p "${HOME}/testconfig"
+if [[ -f /tmp/configmap/foo ]]; then
+    # Copy three configMap entries defined in configmap1 fixture to directory
+    cp /tmp/configmap/* "${HOME}/testconfig"
+else
+    echo "Unable to locate test-configmap fixture files"
+    exit 3
+fi
+
+mkdir -p "${HOME}/testconfig2"
+if [[ -f configmap2/foo  ]]; then
+    # Copy three configMap entries defined in configmap2 fixture to directory
+    cp configmap2/* "${HOME}/testconfig2"
+else
+    echo "Unable to locate test-configmap-2 fixture files"
+    exit 4
+fi
