Implement "pod.network.openshift.io/assign-macvlan" annotation
If a pod has the annotation "pod.network.openshift.io/assign-macvlan=true",
and contains a privileged container, then when setting up the pod,
create a macvlan device on the node's default network interface and
move it into the pod's namespace.

diff --git a/plugins/osdn/ovs/bin/openshift-sdn-ovs b/plugins/osdn/ovs/bin/openshift-sdn-ovs
--- a/plugins/osdn/ovs/bin/openshift-sdn-ovs
+++ b/plugins/osdn/ovs/bin/openshift-sdn-ovs
@@ -8,6 +8,7 @@ net_container=$2
 tenant_id=$3
 ingress_bw=$4
 egress_bw=$5
+macvlan=$6
 
 lockwrap() {
     (
@@ -115,6 +116,16 @@ ensure_subnet_route() {
     add_subnet_route
 }
 
+add_macvlan() {
+    default_dev=$(ip route show | sed -ne 's/^default .* dev \([^ ]*\) .*/\1/p')
+    if [ -z "$default_dev" ]; then
+	echo "Could not find default network interface"
+	exit 1
+    fi
+    ip link add link $default_dev name macvlan0 type macvlan mode private
+    ip link set macvlan0 netns $pid
+}
+
 run() {
     get_ipaddr_pid_veth
     source /run/openshift-sdn/config.env
@@ -124,6 +135,9 @@ run() {
 	    add_ovs_port
 	    add_ovs_flows
 	    add_subnet_route
+	    if [ "$macvlan" = true ]; then
+		add_macvlan
+	    fi
 	    ;;
 
 	update)
